name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore
        run: dotnet restore MauiApp1/MauiApp1.csproj

      - name: Build iOS without signing
        run: |
          dotnet publish MauiApp1/MauiApp1.csproj \
            -f net9.0-ios \
            -c Release \
            -r ios-arm64 \
            -p:EnableCodeSigning=false \
            -p:ArchiveOnBuild=false

      - name: Find app
        run: |
          echo "Procurando .app..."
          find . -type d -name "*.app"

      - name: Create IPA
        run: |
          APP=$(find . -type d -name "*.app" | head -n 1)

          if [ -z "$APP" ]; then
            echo "ERRO: nenhum arquivo .app foi encontrado."
            exit 1
          fi

          echo "APP encontrado: $APP"

          mkdir -p ipa/Payload
          cp -R "$APP" ipa/Payload/MauiApp1.app

          cd ipa
          zip -r ../MauiApp1.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: MauiApp1-IPA
          path: MauiApp1.ipa
